<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ItemDetail;

class ItemDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $products = array(
            array(
                'description' => 'Hydraulic Lifter',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 1500000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Mechanical Lifter',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 800000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Automotive Battery',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 100000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Hydraulic Jack',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 28000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Stationary Jack',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 5000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Socket wrench',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 17500.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Deep socket wrench',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 21000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Heavy duty Socket wrench',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 56000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Diesel Engine',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 560000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Gasoline engine',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 350000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Electric drill',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 20000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Electric grinder',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 8000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Welding machine',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 56000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Torque wrench',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 21000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Air compressor',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 40000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Combination wrench',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 10000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => '2 post car lifter',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 300000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => '4 post car lifter',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 500000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'OBD 2 Scanner',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 200000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Computerized Wheel alignment',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 1000000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Wheel balancer',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 50000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Tire Changing machine',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 70000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Portable Refrigerant recovery Machine',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 200000.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Refrigerant Tank with freon',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 31500.00,
                'category_id' => 13,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Computer (for instructional use)',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 50000.00,
                'category_id' => 14,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Smart TV with installation 50 inches',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 50000.00,
                'category_id' => 14,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Computer (for Instructional use) intel core i7 - Server',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 70000.00,
                'category_id' => 14,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Photoshop License Software',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 200000.00,
                'category_id' => 14,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Java License Software',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 200000.00,
                'category_id' => 14,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Angular License Software',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 200000.00,
                'category_id' => 14,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Microsoft Visual Studio 2019',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 30000.00,
                'category_id' => 14,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Microsoft Office 2017 License Installer',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 1200.00,
                'category_id' => 14,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Cisco Router',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 40000.00,
                'category_id' => 14,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Cisco Switch',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 40000.00,
                'category_id' => 14,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Apple iMac (21.5” i5 /8gb ram / 1tb storage)',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 80000.00,
                'category_id' => 14,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => '3 - Compartment dishwashing sink table with tubular',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 48000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => '4 - layered tubular clean dish rack (slotted)',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 22000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => '4 - Solid Stainless Door Upright Chiller',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 101000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => '4 - Solid Stainless Steel Door Upright Freezer',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 126000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => '4- Layered Plain Rack',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 22000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Combination 4 - Door Upright Chiller and Freezer',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 123000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Compartment dishwashing sink table with tubular bracing',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 48000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Digital Weighing Scale (1kg)',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 20000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Gas Heated baking oven (3 deck)',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 225000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Heavy Duty Food Processor',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 33600.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Heavy Duty Mixer',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 27000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Heavy Duty Stand Mixer',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 18000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Island Type - Exhaust food canopy',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 69000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Island Type 1 compartment sinkable with tubular bracing',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 16000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Island Type prep. With mid and bottom shelves',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 28000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'La Germania Gas Range',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 19500.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Refrigerator 2 Door',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 30000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Stainless Steel grease trap 20 GPM (2 - Chambers)',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 17500.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Vacuum Packaging Machine (DZ-260) (V:220V/60HZ, Motor Power: 370W, Chamber Siza: 385 x 280x120mm (LxWxH), Min. Absolute Pressure: 1Kpa, Sealing Size: 260x8mm, Pump Rate: 20m3h, External Dimension: 480x330x360mm)',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 1250000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Vertical Scale 1M long',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 19000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
            array(
                'description' => 'Wall Mounted Exhaust Hood',
                'article' => null,
                'extra_article' => null,
                'price_catalogue' => 43000.00,
                'category_id' => 15,
                'unit_id' => 12,
                'added_by' => 1,
                'is_approve' => 1,
            ),
        );

        foreach ($products as $p) {
            ItemDetail::create([
                'description' => $p['description'],
                'article' => $p['article'],
                'price_catalogue' => $p['price_catalogue'],
                'category_id' => $p['category_id'],
                'unit_id' => $p['unit_id'],
                'added_by' => $p['added_by'],
                'is_approve' => $p['is_approve']
            ]);
        }
    }
}
